export const skills = {
  frontend: [
    { name: "HTML", icon: "/icons/html.png" },
    { name: "CSS", icon: "/icons/css.png" },
    { name: "Angular", icon: "/icons/angular.png" },
    { name: "JavaScript", icon: "/icons/javascript.png" },
    { name: "React", icon: "/icons/react.png" },
    { name: "Redux", icon: "/icons/redux.png" },
    { name: "Next.js", icon: "/icons/next.png" },
    { name: "Tailwind CSS", icon: "/icons/tailwind.png" },
    { name: "Vue", icon: "/icons/vue.png" },
    { name: "React Three Fiber", icon: "/icons/r3f.png" },
    { name: "Three.js", icon: "/icons/three.png" },
    { name: "GSAP", icon: "/icons/gsap.png" },
  ],
  backend: [
    { name: "Node.js", icon: "/icons/node.png" },
    { name: "Express", icon: "/icons/express.png" },
    { name: "Nest.js", icon: "/icons/nest.png" },
    { name: "MySQL", icon: "/icons/sql.png" },
    { name: "Sequelize", icon: "/icons/sequelize.png" },
    { name: "MongoDB", icon: "/icons/mongo.png" },
    { name: "Mongoose", icon: "/icons/mongoose.png" },
    { name: "REST API", icon: "/icons/api.png" },
    { name: "Python", icon: "/icons/python.png" },
    { name: "Prisma", icon: "/icons/prisma.png" },
    { name: "APIs", icon: "/icons/api.png" },
  ],
  tools: [
    { name: "Git", icon: "/icons/git.png" },
    { name: "GitHub", icon: "/icons/github.png" },
    { name: "Heroku", icon: "/icons/heroku.png" },
    { name: "Netlify", icon: "/icons/netlify.png" },
    { name: "Postman", icon: "/icons/postman.png" },
    { name: "Webpack", icon: "/icons/webpack.png" },
    { name: "TypeScript", icon: "/icons/typescript.png" },
    { name: "Jest", icon: "/icons/jest.png" },
  ],
};
